# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.6
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _CImg.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CImg', [dirname(__file__)])
        except ImportError:
            import _CImg
            return _CImg
        if fp is not None:
            try:
                _mod = imp.load_module('_CImg', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CImg = swig_import_helper()
    del swig_import_helper
else:
    import _CImg
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


cimg_version = _CImg.cimg_version
cimg_OS = _CImg.cimg_OS
cimg_file_separator = _CImg.cimg_file_separator
cimg_verbosity = _CImg.cimg_verbosity
cimg_appname = _CImg.cimg_appname
_cimgdisplay_instance = _CImg._cimgdisplay_instance
_cimg_instance = _CImg._cimg_instance
_cimglist_instance = _CImg._cimglist_instance

def output(file=None):
  return _CImg.output(file)
output = _CImg.output

def info():
  return _CImg.info()
info = _CImg.info

def _exception_mode(*args):
  return _CImg._exception_mode(*args)
_exception_mode = _CImg._exception_mode

def exception_mode(*args):
  return _CImg.exception_mode(*args)
exception_mode = _CImg.exception_mode

def dialog(*args):
  return _CImg.dialog(*args)
dialog = _CImg.dialog

def eval(*args):
  return _CImg.eval(*args)
eval = _CImg.eval
class CImgException(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    _message = _swig_property(_CImg.CImgException__message_get, _CImg.CImgException__message_set)
    def __init__(self, *args): 
        _CImg.CImgException_swiginit(self,_CImg.new_CImgException(*args))
    __swig_destroy__ = _CImg.delete_CImgException
CImgException.what = new_instancemethod(_CImg.CImgException_what,None,CImgException)
CImgException_swigregister = _CImg.CImgException_swigregister
CImgException_swigregister(CImgException)
cvar = _CImg.cvar
t_normal = cvar.t_normal
t_black = cvar.t_black
t_red = cvar.t_red
t_green = cvar.t_green
t_yellow = cvar.t_yellow
t_blue = cvar.t_blue
t_magenta = cvar.t_magenta
t_cyan = cvar.t_cyan
t_white = cvar.t_white
t_bold = cvar.t_bold
t_underscore = cvar.t_underscore

class CImgInstanceException(CImgException):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        _CImg.CImgInstanceException_swiginit(self,_CImg.new_CImgInstanceException(*args))
    __swig_destroy__ = _CImg.delete_CImgInstanceException
CImgInstanceException_swigregister = _CImg.CImgInstanceException_swigregister
CImgInstanceException_swigregister(CImgInstanceException)

class CImgArgumentException(CImgException):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        _CImg.CImgArgumentException_swiginit(self,_CImg.new_CImgArgumentException(*args))
    __swig_destroy__ = _CImg.delete_CImgArgumentException
CImgArgumentException_swigregister = _CImg.CImgArgumentException_swigregister
CImgArgumentException_swigregister(CImgArgumentException)

class CImgIOException(CImgException):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        _CImg.CImgIOException_swiginit(self,_CImg.new_CImgIOException(*args))
    __swig_destroy__ = _CImg.delete_CImgIOException
CImgIOException_swigregister = _CImg.CImgIOException_swigregister
CImgIOException_swigregister(CImgIOException)

class CImgDisplayException(CImgException):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        _CImg.CImgDisplayException_swiginit(self,_CImg.new_CImgDisplayException(*args))
    __swig_destroy__ = _CImg.delete_CImgDisplayException
CImgDisplayException_swigregister = _CImg.CImgDisplayException_swigregister
CImgDisplayException_swigregister(CImgDisplayException)

class CImgWarningException(CImgException):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        _CImg.CImgWarningException_swiginit(self,_CImg.new_CImgWarningException(*args))
    __swig_destroy__ = _CImg.delete_CImgWarningException
CImgWarningException_swigregister = _CImg.CImgWarningException_swigregister
CImgWarningException_swigregister(CImgWarningException)


def warn(*args):
  return _CImg.warn(*args)
warn = _CImg.warn

def system(*args):
  return _CImg.system(*args)
system = _CImg.system

def endianness():
  return _CImg.endianness()
endianness = _CImg.endianness

def float2uint(*args):
  return _CImg.float2uint(*args)
float2uint = _CImg.float2uint

def uint2float(*args):
  return _CImg.uint2float(*args)
uint2float = _CImg.uint2float

def time():
  return _CImg.time()
time = _CImg.time

def tictoc(*args):
  return _CImg.tictoc(*args)
tictoc = _CImg.tictoc

def tic():
  return _CImg.tic()
tic = _CImg.tic

def toc():
  return _CImg.toc()
toc = _CImg.toc

def sleep(*args):
  return _CImg.sleep(*args)
sleep = _CImg.sleep

def _wait(*args):
  return _CImg._wait(*args)
_wait = _CImg._wait

def wait(*args):
  return _CImg.wait(*args)
wait = _CImg.wait

def srand():
  return _CImg.srand()
srand = _CImg.srand

def rand():
  return _CImg.rand()
rand = _CImg.rand

def crand():
  return _CImg.crand()
crand = _CImg.crand

def grand():
  return _CImg.grand()
grand = _CImg.grand

def prand(*args):
  return _CImg.prand(*args)
prand = _CImg.prand

def rol(*args):
  return _CImg.rol(*args)
rol = _CImg.rol

def ror(*args):
  return _CImg.ror(*args)
ror = _CImg.ror

def abs(*args):
  return _CImg.abs(*args)
abs = _CImg.abs

def xln(*args):
  return _CImg.xln(*args)
xln = _CImg.xln

def sinc(*args):
  return _CImg.sinc(*args)
sinc = _CImg.sinc

def mod(*args):
  return _CImg.mod(*args)
mod = _CImg.mod

def log2(*args):
  return _CImg.log2(*args)
log2 = _CImg.log2

def _pythagore(*args):
  return _CImg._pythagore(*args)
_pythagore = _CImg._pythagore

def uncase(*args):
  return _CImg.uncase(*args)
uncase = _CImg.uncase

def atof(*args):
  return _CImg.atof(*args)
atof = _CImg.atof

def strncasecmp(*args):
  return _CImg.strncasecmp(*args)
strncasecmp = _CImg.strncasecmp

def strcasecmp(*args):
  return _CImg.strcasecmp(*args)
strcasecmp = _CImg.strcasecmp

def strpare(*args):
  return _CImg.strpare(*args)
strpare = _CImg.strpare

def strescape(*args):
  return _CImg.strescape(*args)
strescape = _CImg.strescape

def strbuffersize(*args):
  return _CImg.strbuffersize(*args)
strbuffersize = _CImg.strbuffersize

def basename(*args):
  return _CImg.basename(*args)
basename = _CImg.basename

def filenamerand():
  return _CImg.filenamerand()
filenamerand = _CImg.filenamerand

def winformat_string(*args):
  return _CImg.winformat_string(*args)
winformat_string = _CImg.winformat_string

def fopen(*args):
  return _CImg.fopen(*args)
fopen = _CImg.fopen

def fclose(*args):
  return _CImg.fclose(*args)
fclose = _CImg.fclose

def temporary_path(user_path=None, reinit_path=False):
  return _CImg.temporary_path(user_path, reinit_path)
temporary_path = _CImg.temporary_path

def imagemagick_path(user_path=None, reinit_path=False):
  return _CImg.imagemagick_path(user_path, reinit_path)
imagemagick_path = _CImg.imagemagick_path

def graphicsmagick_path(user_path=None, reinit_path=False):
  return _CImg.graphicsmagick_path(user_path, reinit_path)
graphicsmagick_path = _CImg.graphicsmagick_path

def medcon_path(user_path=None, reinit_path=False):
  return _CImg.medcon_path(user_path, reinit_path)
medcon_path = _CImg.medcon_path

def ffmpeg_path(user_path=None, reinit_path=False):
  return _CImg.ffmpeg_path(user_path, reinit_path)
ffmpeg_path = _CImg.ffmpeg_path

def gzip_path(user_path=None, reinit_path=False):
  return _CImg.gzip_path(user_path, reinit_path)
gzip_path = _CImg.gzip_path

def gunzip_path(user_path=None, reinit_path=False):
  return _CImg.gunzip_path(user_path, reinit_path)
gunzip_path = _CImg.gunzip_path

def dcraw_path(user_path=None, reinit_path=False):
  return _CImg.dcraw_path(user_path, reinit_path)
dcraw_path = _CImg.dcraw_path

def wget_path(user_path=None, reinit_path=False):
  return _CImg.wget_path(user_path, reinit_path)
wget_path = _CImg.wget_path

def curl_path(user_path=None, reinit_path=False):
  return _CImg.curl_path(user_path, reinit_path)
curl_path = _CImg.curl_path

def split_filename(*args):
  return _CImg.split_filename(*args)
split_filename = _CImg.split_filename

def number_filename(*args):
  return _CImg.number_filename(*args)
number_filename = _CImg.number_filename

def file_type(*args):
  return _CImg.file_type(*args)
file_type = _CImg.file_type

def load_network_external(*args):
  return _CImg.load_network_external(*args)
load_network_external = _CImg.load_network_external

def option(*args):
  return _CImg.option(*args)
option = _CImg.option

def argument(*args):
  return _CImg.argument(*args)
argument = _CImg.argument
class CImgDisplay(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    _timer = _swig_property(_CImg.CImgDisplay__timer_get, _CImg.CImgDisplay__timer_set)
    _fps_frames = _swig_property(_CImg.CImgDisplay__fps_frames_get, _CImg.CImgDisplay__fps_frames_set)
    _fps_timer = _swig_property(_CImg.CImgDisplay__fps_timer_get, _CImg.CImgDisplay__fps_timer_set)
    _width = _swig_property(_CImg.CImgDisplay__width_get, _CImg.CImgDisplay__width_set)
    _height = _swig_property(_CImg.CImgDisplay__height_get, _CImg.CImgDisplay__height_set)
    _normalization = _swig_property(_CImg.CImgDisplay__normalization_get, _CImg.CImgDisplay__normalization_set)
    _fps_fps = _swig_property(_CImg.CImgDisplay__fps_fps_get, _CImg.CImgDisplay__fps_fps_set)
    _min = _swig_property(_CImg.CImgDisplay__min_get, _CImg.CImgDisplay__min_set)
    _max = _swig_property(_CImg.CImgDisplay__max_get, _CImg.CImgDisplay__max_set)
    _is_fullscreen = _swig_property(_CImg.CImgDisplay__is_fullscreen_get, _CImg.CImgDisplay__is_fullscreen_set)
    _title = _swig_property(_CImg.CImgDisplay__title_get, _CImg.CImgDisplay__title_set)
    _window_width = _swig_property(_CImg.CImgDisplay__window_width_get, _CImg.CImgDisplay__window_width_set)
    _window_height = _swig_property(_CImg.CImgDisplay__window_height_get, _CImg.CImgDisplay__window_height_set)
    _button = _swig_property(_CImg.CImgDisplay__button_get, _CImg.CImgDisplay__button_set)
    _keys = _swig_property(_CImg.CImgDisplay__keys_get, _CImg.CImgDisplay__keys_set)
    _released_keys = _swig_property(_CImg.CImgDisplay__released_keys_get, _CImg.CImgDisplay__released_keys_set)
    _window_x = _swig_property(_CImg.CImgDisplay__window_x_get, _CImg.CImgDisplay__window_x_set)
    _window_y = _swig_property(_CImg.CImgDisplay__window_y_get, _CImg.CImgDisplay__window_y_set)
    _mouse_x = _swig_property(_CImg.CImgDisplay__mouse_x_get, _CImg.CImgDisplay__mouse_x_set)
    _mouse_y = _swig_property(_CImg.CImgDisplay__mouse_y_get, _CImg.CImgDisplay__mouse_y_set)
    _wheel = _swig_property(_CImg.CImgDisplay__wheel_get, _CImg.CImgDisplay__wheel_set)
    _is_closed = _swig_property(_CImg.CImgDisplay__is_closed_get, _CImg.CImgDisplay__is_closed_set)
    _is_resized = _swig_property(_CImg.CImgDisplay__is_resized_get, _CImg.CImgDisplay__is_resized_set)
    _is_moved = _swig_property(_CImg.CImgDisplay__is_moved_get, _CImg.CImgDisplay__is_moved_set)
    _is_event = _swig_property(_CImg.CImgDisplay__is_event_get, _CImg.CImgDisplay__is_event_set)
    _is_keyESC = _swig_property(_CImg.CImgDisplay__is_keyESC_get, _CImg.CImgDisplay__is_keyESC_set)
    _is_keyF1 = _swig_property(_CImg.CImgDisplay__is_keyF1_get, _CImg.CImgDisplay__is_keyF1_set)
    _is_keyF2 = _swig_property(_CImg.CImgDisplay__is_keyF2_get, _CImg.CImgDisplay__is_keyF2_set)
    _is_keyF3 = _swig_property(_CImg.CImgDisplay__is_keyF3_get, _CImg.CImgDisplay__is_keyF3_set)
    _is_keyF4 = _swig_property(_CImg.CImgDisplay__is_keyF4_get, _CImg.CImgDisplay__is_keyF4_set)
    _is_keyF5 = _swig_property(_CImg.CImgDisplay__is_keyF5_get, _CImg.CImgDisplay__is_keyF5_set)
    _is_keyF6 = _swig_property(_CImg.CImgDisplay__is_keyF6_get, _CImg.CImgDisplay__is_keyF6_set)
    _is_keyF7 = _swig_property(_CImg.CImgDisplay__is_keyF7_get, _CImg.CImgDisplay__is_keyF7_set)
    _is_keyF8 = _swig_property(_CImg.CImgDisplay__is_keyF8_get, _CImg.CImgDisplay__is_keyF8_set)
    _is_keyF9 = _swig_property(_CImg.CImgDisplay__is_keyF9_get, _CImg.CImgDisplay__is_keyF9_set)
    _is_keyF10 = _swig_property(_CImg.CImgDisplay__is_keyF10_get, _CImg.CImgDisplay__is_keyF10_set)
    _is_keyF11 = _swig_property(_CImg.CImgDisplay__is_keyF11_get, _CImg.CImgDisplay__is_keyF11_set)
    _is_keyF12 = _swig_property(_CImg.CImgDisplay__is_keyF12_get, _CImg.CImgDisplay__is_keyF12_set)
    _is_keyPAUSE = _swig_property(_CImg.CImgDisplay__is_keyPAUSE_get, _CImg.CImgDisplay__is_keyPAUSE_set)
    _is_key1 = _swig_property(_CImg.CImgDisplay__is_key1_get, _CImg.CImgDisplay__is_key1_set)
    _is_key2 = _swig_property(_CImg.CImgDisplay__is_key2_get, _CImg.CImgDisplay__is_key2_set)
    _is_key3 = _swig_property(_CImg.CImgDisplay__is_key3_get, _CImg.CImgDisplay__is_key3_set)
    _is_key4 = _swig_property(_CImg.CImgDisplay__is_key4_get, _CImg.CImgDisplay__is_key4_set)
    _is_key5 = _swig_property(_CImg.CImgDisplay__is_key5_get, _CImg.CImgDisplay__is_key5_set)
    _is_key6 = _swig_property(_CImg.CImgDisplay__is_key6_get, _CImg.CImgDisplay__is_key6_set)
    _is_key7 = _swig_property(_CImg.CImgDisplay__is_key7_get, _CImg.CImgDisplay__is_key7_set)
    _is_key8 = _swig_property(_CImg.CImgDisplay__is_key8_get, _CImg.CImgDisplay__is_key8_set)
    _is_key9 = _swig_property(_CImg.CImgDisplay__is_key9_get, _CImg.CImgDisplay__is_key9_set)
    _is_key0 = _swig_property(_CImg.CImgDisplay__is_key0_get, _CImg.CImgDisplay__is_key0_set)
    _is_keyBACKSPACE = _swig_property(_CImg.CImgDisplay__is_keyBACKSPACE_get, _CImg.CImgDisplay__is_keyBACKSPACE_set)
    _is_keyINSERT = _swig_property(_CImg.CImgDisplay__is_keyINSERT_get, _CImg.CImgDisplay__is_keyINSERT_set)
    _is_keyHOME = _swig_property(_CImg.CImgDisplay__is_keyHOME_get, _CImg.CImgDisplay__is_keyHOME_set)
    _is_keyPAGEUP = _swig_property(_CImg.CImgDisplay__is_keyPAGEUP_get, _CImg.CImgDisplay__is_keyPAGEUP_set)
    _is_keyTAB = _swig_property(_CImg.CImgDisplay__is_keyTAB_get, _CImg.CImgDisplay__is_keyTAB_set)
    _is_keyQ = _swig_property(_CImg.CImgDisplay__is_keyQ_get, _CImg.CImgDisplay__is_keyQ_set)
    _is_keyW = _swig_property(_CImg.CImgDisplay__is_keyW_get, _CImg.CImgDisplay__is_keyW_set)
    _is_keyE = _swig_property(_CImg.CImgDisplay__is_keyE_get, _CImg.CImgDisplay__is_keyE_set)
    _is_keyR = _swig_property(_CImg.CImgDisplay__is_keyR_get, _CImg.CImgDisplay__is_keyR_set)
    _is_keyT = _swig_property(_CImg.CImgDisplay__is_keyT_get, _CImg.CImgDisplay__is_keyT_set)
    _is_keyY = _swig_property(_CImg.CImgDisplay__is_keyY_get, _CImg.CImgDisplay__is_keyY_set)
    _is_keyU = _swig_property(_CImg.CImgDisplay__is_keyU_get, _CImg.CImgDisplay__is_keyU_set)
    _is_keyI = _swig_property(_CImg.CImgDisplay__is_keyI_get, _CImg.CImgDisplay__is_keyI_set)
    _is_keyO = _swig_property(_CImg.CImgDisplay__is_keyO_get, _CImg.CImgDisplay__is_keyO_set)
    _is_keyP = _swig_property(_CImg.CImgDisplay__is_keyP_get, _CImg.CImgDisplay__is_keyP_set)
    _is_keyDELETE = _swig_property(_CImg.CImgDisplay__is_keyDELETE_get, _CImg.CImgDisplay__is_keyDELETE_set)
    _is_keyEND = _swig_property(_CImg.CImgDisplay__is_keyEND_get, _CImg.CImgDisplay__is_keyEND_set)
    _is_keyPAGEDOWN = _swig_property(_CImg.CImgDisplay__is_keyPAGEDOWN_get, _CImg.CImgDisplay__is_keyPAGEDOWN_set)
    _is_keyCAPSLOCK = _swig_property(_CImg.CImgDisplay__is_keyCAPSLOCK_get, _CImg.CImgDisplay__is_keyCAPSLOCK_set)
    _is_keyA = _swig_property(_CImg.CImgDisplay__is_keyA_get, _CImg.CImgDisplay__is_keyA_set)
    _is_keyS = _swig_property(_CImg.CImgDisplay__is_keyS_get, _CImg.CImgDisplay__is_keyS_set)
    _is_keyD = _swig_property(_CImg.CImgDisplay__is_keyD_get, _CImg.CImgDisplay__is_keyD_set)
    _is_keyF = _swig_property(_CImg.CImgDisplay__is_keyF_get, _CImg.CImgDisplay__is_keyF_set)
    _is_keyG = _swig_property(_CImg.CImgDisplay__is_keyG_get, _CImg.CImgDisplay__is_keyG_set)
    _is_keyH = _swig_property(_CImg.CImgDisplay__is_keyH_get, _CImg.CImgDisplay__is_keyH_set)
    _is_keyJ = _swig_property(_CImg.CImgDisplay__is_keyJ_get, _CImg.CImgDisplay__is_keyJ_set)
    _is_keyK = _swig_property(_CImg.CImgDisplay__is_keyK_get, _CImg.CImgDisplay__is_keyK_set)
    _is_keyL = _swig_property(_CImg.CImgDisplay__is_keyL_get, _CImg.CImgDisplay__is_keyL_set)
    _is_keyENTER = _swig_property(_CImg.CImgDisplay__is_keyENTER_get, _CImg.CImgDisplay__is_keyENTER_set)
    _is_keySHIFTLEFT = _swig_property(_CImg.CImgDisplay__is_keySHIFTLEFT_get, _CImg.CImgDisplay__is_keySHIFTLEFT_set)
    _is_keyZ = _swig_property(_CImg.CImgDisplay__is_keyZ_get, _CImg.CImgDisplay__is_keyZ_set)
    _is_keyX = _swig_property(_CImg.CImgDisplay__is_keyX_get, _CImg.CImgDisplay__is_keyX_set)
    _is_keyC = _swig_property(_CImg.CImgDisplay__is_keyC_get, _CImg.CImgDisplay__is_keyC_set)
    _is_keyV = _swig_property(_CImg.CImgDisplay__is_keyV_get, _CImg.CImgDisplay__is_keyV_set)
    _is_keyB = _swig_property(_CImg.CImgDisplay__is_keyB_get, _CImg.CImgDisplay__is_keyB_set)
    _is_keyN = _swig_property(_CImg.CImgDisplay__is_keyN_get, _CImg.CImgDisplay__is_keyN_set)
    _is_keyM = _swig_property(_CImg.CImgDisplay__is_keyM_get, _CImg.CImgDisplay__is_keyM_set)
    _is_keySHIFTRIGHT = _swig_property(_CImg.CImgDisplay__is_keySHIFTRIGHT_get, _CImg.CImgDisplay__is_keySHIFTRIGHT_set)
    _is_keyARROWUP = _swig_property(_CImg.CImgDisplay__is_keyARROWUP_get, _CImg.CImgDisplay__is_keyARROWUP_set)
    _is_keyCTRLLEFT = _swig_property(_CImg.CImgDisplay__is_keyCTRLLEFT_get, _CImg.CImgDisplay__is_keyCTRLLEFT_set)
    _is_keyAPPLEFT = _swig_property(_CImg.CImgDisplay__is_keyAPPLEFT_get, _CImg.CImgDisplay__is_keyAPPLEFT_set)
    _is_keyALT = _swig_property(_CImg.CImgDisplay__is_keyALT_get, _CImg.CImgDisplay__is_keyALT_set)
    _is_keySPACE = _swig_property(_CImg.CImgDisplay__is_keySPACE_get, _CImg.CImgDisplay__is_keySPACE_set)
    _is_keyALTGR = _swig_property(_CImg.CImgDisplay__is_keyALTGR_get, _CImg.CImgDisplay__is_keyALTGR_set)
    _is_keyAPPRIGHT = _swig_property(_CImg.CImgDisplay__is_keyAPPRIGHT_get, _CImg.CImgDisplay__is_keyAPPRIGHT_set)
    _is_keyMENU = _swig_property(_CImg.CImgDisplay__is_keyMENU_get, _CImg.CImgDisplay__is_keyMENU_set)
    _is_keyCTRLRIGHT = _swig_property(_CImg.CImgDisplay__is_keyCTRLRIGHT_get, _CImg.CImgDisplay__is_keyCTRLRIGHT_set)
    _is_keyARROWLEFT = _swig_property(_CImg.CImgDisplay__is_keyARROWLEFT_get, _CImg.CImgDisplay__is_keyARROWLEFT_set)
    _is_keyARROWDOWN = _swig_property(_CImg.CImgDisplay__is_keyARROWDOWN_get, _CImg.CImgDisplay__is_keyARROWDOWN_set)
    _is_keyARROWRIGHT = _swig_property(_CImg.CImgDisplay__is_keyARROWRIGHT_get, _CImg.CImgDisplay__is_keyARROWRIGHT_set)
    _is_keyPAD0 = _swig_property(_CImg.CImgDisplay__is_keyPAD0_get, _CImg.CImgDisplay__is_keyPAD0_set)
    _is_keyPAD1 = _swig_property(_CImg.CImgDisplay__is_keyPAD1_get, _CImg.CImgDisplay__is_keyPAD1_set)
    _is_keyPAD2 = _swig_property(_CImg.CImgDisplay__is_keyPAD2_get, _CImg.CImgDisplay__is_keyPAD2_set)
    _is_keyPAD3 = _swig_property(_CImg.CImgDisplay__is_keyPAD3_get, _CImg.CImgDisplay__is_keyPAD3_set)
    _is_keyPAD4 = _swig_property(_CImg.CImgDisplay__is_keyPAD4_get, _CImg.CImgDisplay__is_keyPAD4_set)
    _is_keyPAD5 = _swig_property(_CImg.CImgDisplay__is_keyPAD5_get, _CImg.CImgDisplay__is_keyPAD5_set)
    _is_keyPAD6 = _swig_property(_CImg.CImgDisplay__is_keyPAD6_get, _CImg.CImgDisplay__is_keyPAD6_set)
    _is_keyPAD7 = _swig_property(_CImg.CImgDisplay__is_keyPAD7_get, _CImg.CImgDisplay__is_keyPAD7_set)
    _is_keyPAD8 = _swig_property(_CImg.CImgDisplay__is_keyPAD8_get, _CImg.CImgDisplay__is_keyPAD8_set)
    _is_keyPAD9 = _swig_property(_CImg.CImgDisplay__is_keyPAD9_get, _CImg.CImgDisplay__is_keyPAD9_set)
    _is_keyPADADD = _swig_property(_CImg.CImgDisplay__is_keyPADADD_get, _CImg.CImgDisplay__is_keyPADADD_set)
    _is_keyPADSUB = _swig_property(_CImg.CImgDisplay__is_keyPADSUB_get, _CImg.CImgDisplay__is_keyPADSUB_set)
    _is_keyPADMUL = _swig_property(_CImg.CImgDisplay__is_keyPADMUL_get, _CImg.CImgDisplay__is_keyPADMUL_set)
    _is_keyPADDIV = _swig_property(_CImg.CImgDisplay__is_keyPADDIV_get, _CImg.CImgDisplay__is_keyPADDIV_set)
    __swig_destroy__ = _CImg.delete_CImgDisplay
    def __init__(self, *args): 
        _CImg.CImgDisplay_swiginit(self,_CImg.new_CImgDisplay(*args))
    _no_display_exception = staticmethod(_CImg.CImgDisplay__no_display_exception)
    empty = staticmethod(_CImg.CImgDisplay_empty)
    _fitscreen = staticmethod(_CImg.CImgDisplay__fitscreen)
    def __nonzero__(self):
        return _CImg.CImgDisplay___nonzero__(self)
    __bool__ = __nonzero__


    screen_width = staticmethod(_CImg.CImgDisplay_screen_width)
    screen_height = staticmethod(_CImg.CImgDisplay_screen_height)
    keycode = staticmethod(_CImg.CImgDisplay_keycode)
    wait = staticmethod(_CImg.CImgDisplay_wait)
    wait_all = staticmethod(_CImg.CImgDisplay_wait_all)
CImgDisplay.assign = new_instancemethod(_CImg.CImgDisplay_assign,None,CImgDisplay)
CImgDisplay.is_empty = new_instancemethod(_CImg.CImgDisplay_is_empty,None,CImgDisplay)
CImgDisplay.is_closed = new_instancemethod(_CImg.CImgDisplay_is_closed,None,CImgDisplay)
CImgDisplay.is_resized = new_instancemethod(_CImg.CImgDisplay_is_resized,None,CImgDisplay)
CImgDisplay.is_moved = new_instancemethod(_CImg.CImgDisplay_is_moved,None,CImgDisplay)
CImgDisplay.is_event = new_instancemethod(_CImg.CImgDisplay_is_event,None,CImgDisplay)
CImgDisplay.is_fullscreen = new_instancemethod(_CImg.CImgDisplay_is_fullscreen,None,CImgDisplay)
CImgDisplay.is_key = new_instancemethod(_CImg.CImgDisplay_is_key,None,CImgDisplay)
CImgDisplay.is_key_sequence = new_instancemethod(_CImg.CImgDisplay_is_key_sequence,None,CImgDisplay)
CImgDisplay.is_keyESC = new_instancemethod(_CImg.CImgDisplay_is_keyESC,None,CImgDisplay)
CImgDisplay.is_keyF1 = new_instancemethod(_CImg.CImgDisplay_is_keyF1,None,CImgDisplay)
CImgDisplay.is_keyF2 = new_instancemethod(_CImg.CImgDisplay_is_keyF2,None,CImgDisplay)
CImgDisplay.is_keyF3 = new_instancemethod(_CImg.CImgDisplay_is_keyF3,None,CImgDisplay)
CImgDisplay.is_keyF4 = new_instancemethod(_CImg.CImgDisplay_is_keyF4,None,CImgDisplay)
CImgDisplay.is_keyF5 = new_instancemethod(_CImg.CImgDisplay_is_keyF5,None,CImgDisplay)
CImgDisplay.is_keyF6 = new_instancemethod(_CImg.CImgDisplay_is_keyF6,None,CImgDisplay)
CImgDisplay.is_keyF7 = new_instancemethod(_CImg.CImgDisplay_is_keyF7,None,CImgDisplay)
CImgDisplay.is_keyF8 = new_instancemethod(_CImg.CImgDisplay_is_keyF8,None,CImgDisplay)
CImgDisplay.is_keyF9 = new_instancemethod(_CImg.CImgDisplay_is_keyF9,None,CImgDisplay)
CImgDisplay.is_keyF10 = new_instancemethod(_CImg.CImgDisplay_is_keyF10,None,CImgDisplay)
CImgDisplay.is_keyF11 = new_instancemethod(_CImg.CImgDisplay_is_keyF11,None,CImgDisplay)
CImgDisplay.is_keyF12 = new_instancemethod(_CImg.CImgDisplay_is_keyF12,None,CImgDisplay)
CImgDisplay.is_keyPAUSE = new_instancemethod(_CImg.CImgDisplay_is_keyPAUSE,None,CImgDisplay)
CImgDisplay.is_key1 = new_instancemethod(_CImg.CImgDisplay_is_key1,None,CImgDisplay)
CImgDisplay.is_key2 = new_instancemethod(_CImg.CImgDisplay_is_key2,None,CImgDisplay)
CImgDisplay.is_key3 = new_instancemethod(_CImg.CImgDisplay_is_key3,None,CImgDisplay)
CImgDisplay.is_key4 = new_instancemethod(_CImg.CImgDisplay_is_key4,None,CImgDisplay)
CImgDisplay.is_key5 = new_instancemethod(_CImg.CImgDisplay_is_key5,None,CImgDisplay)
CImgDisplay.is_key6 = new_instancemethod(_CImg.CImgDisplay_is_key6,None,CImgDisplay)
CImgDisplay.is_key7 = new_instancemethod(_CImg.CImgDisplay_is_key7,None,CImgDisplay)
CImgDisplay.is_key8 = new_instancemethod(_CImg.CImgDisplay_is_key8,None,CImgDisplay)
CImgDisplay.is_key9 = new_instancemethod(_CImg.CImgDisplay_is_key9,None,CImgDisplay)
CImgDisplay.is_key0 = new_instancemethod(_CImg.CImgDisplay_is_key0,None,CImgDisplay)
CImgDisplay.is_keyBACKSPACE = new_instancemethod(_CImg.CImgDisplay_is_keyBACKSPACE,None,CImgDisplay)
CImgDisplay.is_keyINSERT = new_instancemethod(_CImg.CImgDisplay_is_keyINSERT,None,CImgDisplay)
CImgDisplay.is_keyHOME = new_instancemethod(_CImg.CImgDisplay_is_keyHOME,None,CImgDisplay)
CImgDisplay.is_keyPAGEUP = new_instancemethod(_CImg.CImgDisplay_is_keyPAGEUP,None,CImgDisplay)
CImgDisplay.is_keyTAB = new_instancemethod(_CImg.CImgDisplay_is_keyTAB,None,CImgDisplay)
CImgDisplay.is_keyQ = new_instancemethod(_CImg.CImgDisplay_is_keyQ,None,CImgDisplay)
CImgDisplay.is_keyW = new_instancemethod(_CImg.CImgDisplay_is_keyW,None,CImgDisplay)
CImgDisplay.is_keyE = new_instancemethod(_CImg.CImgDisplay_is_keyE,None,CImgDisplay)
CImgDisplay.is_keyR = new_instancemethod(_CImg.CImgDisplay_is_keyR,None,CImgDisplay)
CImgDisplay.is_keyT = new_instancemethod(_CImg.CImgDisplay_is_keyT,None,CImgDisplay)
CImgDisplay.is_keyY = new_instancemethod(_CImg.CImgDisplay_is_keyY,None,CImgDisplay)
CImgDisplay.is_keyU = new_instancemethod(_CImg.CImgDisplay_is_keyU,None,CImgDisplay)
CImgDisplay.is_keyI = new_instancemethod(_CImg.CImgDisplay_is_keyI,None,CImgDisplay)
CImgDisplay.is_keyO = new_instancemethod(_CImg.CImgDisplay_is_keyO,None,CImgDisplay)
CImgDisplay.is_keyP = new_instancemethod(_CImg.CImgDisplay_is_keyP,None,CImgDisplay)
CImgDisplay.is_keyDELETE = new_instancemethod(_CImg.CImgDisplay_is_keyDELETE,None,CImgDisplay)
CImgDisplay.is_keyEND = new_instancemethod(_CImg.CImgDisplay_is_keyEND,None,CImgDisplay)
CImgDisplay.is_keyPAGEDOWN = new_instancemethod(_CImg.CImgDisplay_is_keyPAGEDOWN,None,CImgDisplay)
CImgDisplay.is_keyCAPSLOCK = new_instancemethod(_CImg.CImgDisplay_is_keyCAPSLOCK,None,CImgDisplay)
CImgDisplay.is_keyA = new_instancemethod(_CImg.CImgDisplay_is_keyA,None,CImgDisplay)
CImgDisplay.is_keyS = new_instancemethod(_CImg.CImgDisplay_is_keyS,None,CImgDisplay)
CImgDisplay.is_keyD = new_instancemethod(_CImg.CImgDisplay_is_keyD,None,CImgDisplay)
CImgDisplay.is_keyF = new_instancemethod(_CImg.CImgDisplay_is_keyF,None,CImgDisplay)
CImgDisplay.is_keyG = new_instancemethod(_CImg.CImgDisplay_is_keyG,None,CImgDisplay)
CImgDisplay.is_keyH = new_instancemethod(_CImg.CImgDisplay_is_keyH,None,CImgDisplay)
CImgDisplay.is_keyJ = new_instancemethod(_CImg.CImgDisplay_is_keyJ,None,CImgDisplay)
CImgDisplay.is_keyK = new_instancemethod(_CImg.CImgDisplay_is_keyK,None,CImgDisplay)
CImgDisplay.is_keyL = new_instancemethod(_CImg.CImgDisplay_is_keyL,None,CImgDisplay)
CImgDisplay.is_keyENTER = new_instancemethod(_CImg.CImgDisplay_is_keyENTER,None,CImgDisplay)
CImgDisplay.is_keySHIFTLEFT = new_instancemethod(_CImg.CImgDisplay_is_keySHIFTLEFT,None,CImgDisplay)
CImgDisplay.is_keyZ = new_instancemethod(_CImg.CImgDisplay_is_keyZ,None,CImgDisplay)
CImgDisplay.is_keyX = new_instancemethod(_CImg.CImgDisplay_is_keyX,None,CImgDisplay)
CImgDisplay.is_keyC = new_instancemethod(_CImg.CImgDisplay_is_keyC,None,CImgDisplay)
CImgDisplay.is_keyV = new_instancemethod(_CImg.CImgDisplay_is_keyV,None,CImgDisplay)
CImgDisplay.is_keyB = new_instancemethod(_CImg.CImgDisplay_is_keyB,None,CImgDisplay)
CImgDisplay.is_keyN = new_instancemethod(_CImg.CImgDisplay_is_keyN,None,CImgDisplay)
CImgDisplay.is_keyM = new_instancemethod(_CImg.CImgDisplay_is_keyM,None,CImgDisplay)
CImgDisplay.is_keySHIFTRIGHT = new_instancemethod(_CImg.CImgDisplay_is_keySHIFTRIGHT,None,CImgDisplay)
CImgDisplay.is_keyARROWUP = new_instancemethod(_CImg.CImgDisplay_is_keyARROWUP,None,CImgDisplay)
CImgDisplay.is_keyCTRLLEFT = new_instancemethod(_CImg.CImgDisplay_is_keyCTRLLEFT,None,CImgDisplay)
CImgDisplay.is_keyAPPLEFT = new_instancemethod(_CImg.CImgDisplay_is_keyAPPLEFT,None,CImgDisplay)
CImgDisplay.is_keyALT = new_instancemethod(_CImg.CImgDisplay_is_keyALT,None,CImgDisplay)
CImgDisplay.is_keySPACE = new_instancemethod(_CImg.CImgDisplay_is_keySPACE,None,CImgDisplay)
CImgDisplay.is_keyALTGR = new_instancemethod(_CImg.CImgDisplay_is_keyALTGR,None,CImgDisplay)
CImgDisplay.is_keyAPPRIGHT = new_instancemethod(_CImg.CImgDisplay_is_keyAPPRIGHT,None,CImgDisplay)
CImgDisplay.is_keyMENU = new_instancemethod(_CImg.CImgDisplay_is_keyMENU,None,CImgDisplay)
CImgDisplay.is_keyCTRLRIGHT = new_instancemethod(_CImg.CImgDisplay_is_keyCTRLRIGHT,None,CImgDisplay)
CImgDisplay.is_keyARROWLEFT = new_instancemethod(_CImg.CImgDisplay_is_keyARROWLEFT,None,CImgDisplay)
CImgDisplay.is_keyARROWDOWN = new_instancemethod(_CImg.CImgDisplay_is_keyARROWDOWN,None,CImgDisplay)
CImgDisplay.is_keyARROWRIGHT = new_instancemethod(_CImg.CImgDisplay_is_keyARROWRIGHT,None,CImgDisplay)
CImgDisplay.is_keyPAD0 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD0,None,CImgDisplay)
CImgDisplay.is_keyPAD1 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD1,None,CImgDisplay)
CImgDisplay.is_keyPAD2 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD2,None,CImgDisplay)
CImgDisplay.is_keyPAD3 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD3,None,CImgDisplay)
CImgDisplay.is_keyPAD4 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD4,None,CImgDisplay)
CImgDisplay.is_keyPAD5 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD5,None,CImgDisplay)
CImgDisplay.is_keyPAD6 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD6,None,CImgDisplay)
CImgDisplay.is_keyPAD7 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD7,None,CImgDisplay)
CImgDisplay.is_keyPAD8 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD8,None,CImgDisplay)
CImgDisplay.is_keyPAD9 = new_instancemethod(_CImg.CImgDisplay_is_keyPAD9,None,CImgDisplay)
CImgDisplay.is_keyPADADD = new_instancemethod(_CImg.CImgDisplay_is_keyPADADD,None,CImgDisplay)
CImgDisplay.is_keyPADSUB = new_instancemethod(_CImg.CImgDisplay_is_keyPADSUB,None,CImgDisplay)
CImgDisplay.is_keyPADMUL = new_instancemethod(_CImg.CImgDisplay_is_keyPADMUL,None,CImgDisplay)
CImgDisplay.is_keyPADDIV = new_instancemethod(_CImg.CImgDisplay_is_keyPADDIV,None,CImgDisplay)
CImgDisplay.width = new_instancemethod(_CImg.CImgDisplay_width,None,CImgDisplay)
CImgDisplay.height = new_instancemethod(_CImg.CImgDisplay_height,None,CImgDisplay)
CImgDisplay.normalization = new_instancemethod(_CImg.CImgDisplay_normalization,None,CImgDisplay)
CImgDisplay.title = new_instancemethod(_CImg.CImgDisplay_title,None,CImgDisplay)
CImgDisplay.window_width = new_instancemethod(_CImg.CImgDisplay_window_width,None,CImgDisplay)
CImgDisplay.window_height = new_instancemethod(_CImg.CImgDisplay_window_height,None,CImgDisplay)
CImgDisplay.window_x = new_instancemethod(_CImg.CImgDisplay_window_x,None,CImgDisplay)
CImgDisplay.window_y = new_instancemethod(_CImg.CImgDisplay_window_y,None,CImgDisplay)
CImgDisplay.mouse_x = new_instancemethod(_CImg.CImgDisplay_mouse_x,None,CImgDisplay)
CImgDisplay.mouse_y = new_instancemethod(_CImg.CImgDisplay_mouse_y,None,CImgDisplay)
CImgDisplay.button = new_instancemethod(_CImg.CImgDisplay_button,None,CImgDisplay)
CImgDisplay.wheel = new_instancemethod(_CImg.CImgDisplay_wheel,None,CImgDisplay)
CImgDisplay.key = new_instancemethod(_CImg.CImgDisplay_key,None,CImgDisplay)
CImgDisplay.released_key = new_instancemethod(_CImg.CImgDisplay_released_key,None,CImgDisplay)
CImgDisplay.frames_per_second = new_instancemethod(_CImg.CImgDisplay_frames_per_second,None,CImgDisplay)
CImgDisplay.show = new_instancemethod(_CImg.CImgDisplay_show,None,CImgDisplay)
CImgDisplay.close = new_instancemethod(_CImg.CImgDisplay_close,None,CImgDisplay)
CImgDisplay.move = new_instancemethod(_CImg.CImgDisplay_move,None,CImgDisplay)
CImgDisplay.resize = new_instancemethod(_CImg.CImgDisplay_resize,None,CImgDisplay)
CImgDisplay.set_normalization = new_instancemethod(_CImg.CImgDisplay_set_normalization,None,CImgDisplay)
CImgDisplay.set_title = new_instancemethod(_CImg.CImgDisplay_set_title,None,CImgDisplay)
CImgDisplay.set_fullscreen = new_instancemethod(_CImg.CImgDisplay_set_fullscreen,None,CImgDisplay)
CImgDisplay.toggle_fullscreen = new_instancemethod(_CImg.CImgDisplay_toggle_fullscreen,None,CImgDisplay)
CImgDisplay.show_mouse = new_instancemethod(_CImg.CImgDisplay_show_mouse,None,CImgDisplay)
CImgDisplay.hide_mouse = new_instancemethod(_CImg.CImgDisplay_hide_mouse,None,CImgDisplay)
CImgDisplay.set_mouse = new_instancemethod(_CImg.CImgDisplay_set_mouse,None,CImgDisplay)
CImgDisplay.set_button = new_instancemethod(_CImg.CImgDisplay_set_button,None,CImgDisplay)
CImgDisplay.set_wheel = new_instancemethod(_CImg.CImgDisplay_set_wheel,None,CImgDisplay)
CImgDisplay.set_key = new_instancemethod(_CImg.CImgDisplay_set_key,None,CImgDisplay)
CImgDisplay.flush = new_instancemethod(_CImg.CImgDisplay_flush,None,CImgDisplay)
CImgDisplay.paint = new_instancemethod(_CImg.CImgDisplay_paint,None,CImgDisplay)
CImgDisplay_swigregister = _CImg.CImgDisplay_swigregister
CImgDisplay_swigregister(CImgDisplay)
keyESC = cvar.keyESC
keyF1 = cvar.keyF1
keyF2 = cvar.keyF2
keyF3 = cvar.keyF3
keyF4 = cvar.keyF4
keyF5 = cvar.keyF5
keyF6 = cvar.keyF6
keyF7 = cvar.keyF7
keyF8 = cvar.keyF8
keyF9 = cvar.keyF9
keyF10 = cvar.keyF10
keyF11 = cvar.keyF11
keyF12 = cvar.keyF12
keyPAUSE = cvar.keyPAUSE
key1 = cvar.key1
key2 = cvar.key2
key3 = cvar.key3
key4 = cvar.key4
key5 = cvar.key5
key6 = cvar.key6
key7 = cvar.key7
key8 = cvar.key8
key9 = cvar.key9
key0 = cvar.key0
keyBACKSPACE = cvar.keyBACKSPACE
keyINSERT = cvar.keyINSERT
keyHOME = cvar.keyHOME
keyPAGEUP = cvar.keyPAGEUP
keyTAB = cvar.keyTAB
keyQ = cvar.keyQ
keyW = cvar.keyW
keyE = cvar.keyE
keyR = cvar.keyR
keyT = cvar.keyT
keyY = cvar.keyY
keyU = cvar.keyU
keyI = cvar.keyI
keyO = cvar.keyO
keyP = cvar.keyP
keyDELETE = cvar.keyDELETE
keyEND = cvar.keyEND
keyPAGEDOWN = cvar.keyPAGEDOWN
keyCAPSLOCK = cvar.keyCAPSLOCK
keyA = cvar.keyA
keyS = cvar.keyS
keyD = cvar.keyD
keyF = cvar.keyF
keyG = cvar.keyG
keyH = cvar.keyH
keyJ = cvar.keyJ
keyK = cvar.keyK
keyL = cvar.keyL
keyENTER = cvar.keyENTER
keySHIFTLEFT = cvar.keySHIFTLEFT
keyZ = cvar.keyZ
keyX = cvar.keyX
keyC = cvar.keyC
keyV = cvar.keyV
keyB = cvar.keyB
keyN = cvar.keyN
keyM = cvar.keyM
keySHIFTRIGHT = cvar.keySHIFTRIGHT
keyARROWUP = cvar.keyARROWUP
keyCTRLLEFT = cvar.keyCTRLLEFT
keyAPPLEFT = cvar.keyAPPLEFT
keyALT = cvar.keyALT
keySPACE = cvar.keySPACE
keyALTGR = cvar.keyALTGR
keyAPPRIGHT = cvar.keyAPPRIGHT
keyMENU = cvar.keyMENU
keyCTRLRIGHT = cvar.keyCTRLRIGHT
keyARROWLEFT = cvar.keyARROWLEFT
keyARROWDOWN = cvar.keyARROWDOWN
keyARROWRIGHT = cvar.keyARROWRIGHT
keyPAD0 = cvar.keyPAD0
keyPAD1 = cvar.keyPAD1
keyPAD2 = cvar.keyPAD2
keyPAD3 = cvar.keyPAD3
keyPAD4 = cvar.keyPAD4
keyPAD5 = cvar.keyPAD5
keyPAD6 = cvar.keyPAD6
keyPAD7 = cvar.keyPAD7
keyPAD8 = cvar.keyPAD8
keyPAD9 = cvar.keyPAD9
keyPADADD = cvar.keyPADADD
keyPADSUB = cvar.keyPADSUB
keyPADMUL = cvar.keyPADMUL
keyPADDIV = cvar.keyPADDIV
PI = cvar.PI
font10x13 = cvar.font10x13
font12x24 = cvar.font12x24
font16x32 = cvar.font16x32
font29x57 = cvar.font29x57
logo40x38 = cvar.logo40x38

def CImgDisplay__no_display_exception():
  return _CImg.CImgDisplay__no_display_exception()
CImgDisplay__no_display_exception = _CImg.CImgDisplay__no_display_exception

def CImgDisplay_empty():
  return _CImg.CImgDisplay_empty()
CImgDisplay_empty = _CImg.CImgDisplay_empty

def CImgDisplay__fitscreen(*args):
  return _CImg.CImgDisplay__fitscreen(*args)
CImgDisplay__fitscreen = _CImg.CImgDisplay__fitscreen

def CImgDisplay_screen_width():
  return _CImg.CImgDisplay_screen_width()
CImgDisplay_screen_width = _CImg.CImgDisplay_screen_width

def CImgDisplay_screen_height():
  return _CImg.CImgDisplay_screen_height()
CImgDisplay_screen_height = _CImg.CImgDisplay_screen_height

def CImgDisplay_keycode(*args):
  return _CImg.CImgDisplay_keycode(*args)
CImgDisplay_keycode = _CImg.CImgDisplay_keycode

def CImgDisplay_wait(*args):
  return _CImg.CImgDisplay_wait(*args)
CImgDisplay_wait = _CImg.CImgDisplay_wait

def CImgDisplay_wait_all():
  return _CImg.CImgDisplay_wait_all()
CImgDisplay_wait_all = _CImg.CImgDisplay_wait_all



